spring:
  datasource:
    url: jdbc:mysql://localhost:3334/spring-jwt?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
dialect: org.hibernate.dialect.MySQL5Dialect